#1.Create a 1D NumPy array containing the integers from 0 to 9.

In [1]:
import numpy as np
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


#2.Create a 2D NumPy array of shape (3, 3) with values ranging from 1 to 9.

In [2]:
arr=np.arange(1,10).reshape(3,3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#3.Create a 3x3 identity matrix using NumPy.

In [ ]:
arr=np.eye(3,3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#4.Generate a NumPy array of 10 random numbers between 0 and 1.

In [3]:
import random
arr=np.random.rand(10)
print(arr)

[0.61049198 0.55961134 0.42408831 0.77682992 0.42062617 0.3300603
 0.02059003 0.69547061 0.78805967 0.84569937]


#5.Create an array of 10 zeros and another of 10 ones.

In [ ]:
arr=np.zeros(10)
print(arr)
print('-------------------------')
arr1=np.ones(10)
print(arr1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
-------------------------
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#6.Given the array a = np.array([10, 20, 30, 40, 50]), access the third element.

In [ ]:
a=np.array([10, 20, 30, 40, 50])
print(a[2])

30


#7.Create a 4x4 matrix and access the element at the second row, third column.

In [ ]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(arr)
print('--------------------------')
print(arr[1,2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
--------------------------
7


#8.Access the last element of the array a = np.array([5, 10, 15, 20, 25]).

In [ ]:
a=np.array([5, 10, 15, 20, 25])
print(a[-1])

25


#9.For the array a = np.array([1, 3, 5, 7, 9, 11]), access the elements at indices 1, 3, and 4.


In [6]:
a=np.array([1, 3, 5, 7, 9, 11])
b=a[[1,3,4]]
print(b)

[3 7 9]


#10.Create a 3D array of shape (2, 2, 2) and access the element at position (1, 1, 1).

In [7]:
arr=np.array([[[1,2],[3,4]],
              [[5,6],[7,8]]])
print(arr)
print('-------------------------')
print(arr[1,1,1])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
-------------------------
8


#11.Given the array a = np.array([2, 4, 6, 8, 10, 12]), slice it to get the first 3 elements.

In [ ]:
a=np.array([2, 4, 6, 8, 10, 12])
print(a[:3])

[2 4 6]


#12.Create a 4x4 array and slice it to get the first two rows and last two columns.

In [ ]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(arr)
print('-------------------------')
print(arr[:2,2:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
-------------------------
[[3 4]
 [7 8]]


#13.For the array a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), slice it to get every second element.

In [ ]:
a=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a[::2])

[0 2 4 6 8]


#14.Slice the last two elements from each row of a 3x4 array.

In [ ]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)
print('-------------------------')
print(arr[:,2:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
-------------------------
[[ 3  4]
 [ 7  8]
 [11 12]]


#15.Create a 5x5 matrix and slice out the inner 3x3 matrix.

In [ ]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print(arr)
print('-------------------------')
print(arr[1:4,1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
-------------------------
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


#16.Create an array of integers from 0 to 5 and change its data type to float.

In [ ]:
arr=np.array([0,1,2,3,4,5])
print(arr)
print('-------------------------')
arr1=arr.astype('f')
print(arr1)

[0 1 2 3 4 5]
-------------------------
[0. 1. 2. 3. 4. 5.]


#17.Create a NumPy array of shape (3, 3) with boolean values (True/False).

In [ ]:
arr=np.array([['true','false','true'],['false','true','false'],['true','false','true']])
print(arr)


[['true' 'false' 'true']
 ['false' 'true' 'false']
 ['true' 'false' 'true']]


#18.Create an array of complex numbers (e.g., [1+2j, 3+4j, 5+6j]).

In [ ]:
a=np.array([[1+2j,2+1j],[1+5j,2+4j]])
print(a)

[[1.+2.j 2.+1.j]
 [1.+5.j 2.+4.j]]


#19.given an array of strings(eg.,["1","2","3"]),convert it to an array of integers.

In [8]:
arr=np.array(['1','2','3'])
arr1=arr.astype(int)
print(arr1)

[1 2 3]


#20.create an array of float values and then convert it to an integer type.

In [11]:
arr=np.array([1.1,2.2,3.3])
print(arr.dtype)
arr1=arr.astype('i')
print(arr1.dtype)

float64
int32
